"""Relationship between Station and Status.

Revision ID: 4e5f3afbc9c6
Revises: ea4c5954c633
Create Date: 2023-09-22 14:58:55.506926

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4e5f3afbc9c6"
down_revision: Union[str, None] = "ea4c5954c633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
