"""Add geometry

Revision ID: 758e7c5cf2e3
Revises: f09cc5f1b117
Create Date: 2023-10-02 10:05:02.547615

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "758e7c5cf2e3"
down_revision: Union[str, None] = "f09cc5f1b117"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "arrondissement",
        sa.Column("c_ar", sa.BigInteger(), nullable=False),
        sa.Column("l_ar", sa.String(length=30), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("c_ar"),
    )
    op.create_index(
        "idx_arrondissement_geometry",
        "arrondissement",
        ["geometry"],
        unique=False,
        postgresql_using="gist",
    )
    op.add_column(
        "station_information",
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
    )
    # op.create_index('idx_station_information_geometry', 'station_information', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_station_information_geometry', table_name='station_information', postgresql_using='gist')
    op.drop_column("station_information", "geometry")
    op.drop_index(
        "idx_arrondissement_geometry",
        table_name="arrondissement",
        postgresql_using="gist",
    )
    op.drop_table("arrondissement")
    # ### end Alembic commands ###
