# Use an official Python runtime as the base image
FROM python:3.9.17-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the poetry.lock and pyproject.toml files
COPY pyproject.toml poetry.lock /app/

# Install poetry
RUN pip install poetry==1.4.2 --no-cache-dir

# Do not use virtual environment
RUN poetry config virtualenvs.create false

# Install project dependencies using poetry
RUN poetry install --no-root --no-cache
