name: Version Bump

on:
  pull_request:
    branches:
      - main*
    types:
      - closed

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title and Determine Version Bump
        id: check-pr-title
        if: github.event.pull_request.merged == true
        run: |
          PR_TITLE=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
          echo "PR Title: $PR_TITLE"
          if [[ $PR_TITLE =~ (patch|minor|major) ]]; then
            echo "Version bump keyword found: ${BASH_REMATCH[0]}"
            echo "bump_version=${BASH_REMATCH[0]}" >> $GITHUB_OUTPUT
          else
            echo "No version bump keyword (patch, minor, or major) found in the PR title."
            exit 1
          fi
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.17

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.2

      - name: Bump Version and tag
        if: steps.check-pr-title.outputs.bump_version
        env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          VERSION_BUMP="${{ steps.check-pr-title.outputs.bump_version }}"
          poetry version "$VERSION_BUMP"
          RELEASE_VERSION=$(poetry version -s)
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git commit -m "Bump version to $RELEASE_VERSION" pyproject.toml
          git push -f origin HEAD:${{ github.base_ref }}
          git tag -a "v$VERSION_BUMP" -m "Version $VERSION_BUMP"
          git push -f origin "v$VERSION_BUMP"
