name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile.base
          push: true
          tags: clementcome/velib_base:${{ github.ref }},clementcome/velib_base:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          push: true
          tags: clementcome/velib:${{ github.ref }},clementcome/velib:latest

  publish-python-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9.17
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.17
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.2
      - name: Build and publish
        run: |
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
