name: Development tag

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for the tag'
        required: true
        default: 'Release candidate for feature X'

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install python 3.9.17
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.17
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.2
      - name: Tag
        run: |
          CURRENT_VERSION=$(poetry version -s)
          echo "Current version: $CURRENT_VERSION"
          RELEASE_CANDIDATE=$(poetry version prerelese -s)
          echo "Release candidate: $RELEASE_CANDIDATE"
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git tag -a "v$RELEASE_CANDIDATE" -m "Release candidate $RELEASE_CANDIDATE - ${{ github.event.inputs.message }}"
          git push -f origin "v$RELEASE_CANDIDATE"
