name: Development tag

on:
  workflow_dispatch:
    inputs:
      release-candidate:
        description: 'Release candidate version'
        required: true
        default: '1'

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install python 3.9.17
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.17
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.2
      - name: Tag
        run: |
          CURRENT_VERSION=$(poetry version -s)
          RELEASE_CANDIDATE=${{ github.event.inputs.release-candidate }}
          echo "Current version: $CURRENT_VERSION"
          NEW_VERSION=${CURRENT_VERSION}rc${RELEASE_CANDIDATE}
          echo "New version: $NEW_VERSION"
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git tag -a "v$NEW_VERSION" -m "Version $NEW_VERSION"
          git push -f origin "v$NEW_VERSION"
