name: Validation

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.17
    - name: Prepare environment for testing
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.4.2
        poetry config virtualenvs.create false
        poetry install --with=test
    - name: Test with pytest and generate coverage report
      run: pytest

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Prepare environment for linting
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.4.2
        poetry config virtualenvs.create false
        poetry install --with=lint
    - name: Lint with ruff
      run: ruff check velib_spot_predictor
