name: Validation

on:
  push:
    branches:
      - "!main"

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Prepare environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.4.2
        poetry config virtualenvs.create false
    - name: Install dependencies
      run: poetry install --with=test
    - name: Test with pytest and generate coverage report
      run: pytest

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Prepare environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry==1.4.2
        poetry config virtualenvs.create false
    - name: Install dependencies
      run: poetry install --with=lint
    - name: Lint with flake8
      run: ruff check velib_spot_predictor
