name: release-control

on:
  workflow_dispatch
  # pull_request:
  #   branches:
  #     - main
  #   types: [opened, synchronize]
    

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Grant executable permission to script
      run: chmod +x ./.github/scripts/release-control.sh
    - name: Set up Python 3.9
      run: ./.github/scripts/release-control.sh
      
