name: release-control

on:
  pull_request:
    branches:
      - main-test-ci-cd
    

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Title and Determine Version Bump
      id: check-pr-title
      run: |
        PR_TITLE=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
        if [[ $PR_TITLE =~ (patch|minor|major) ]]; then
          echo "::set-output name=bump_version::${BASH_REMATCH[0]}"
        else
          echo "No version bump keyword (patch, minor, or major) found in the PR title."
          exit 1
        fi
    - name: Build and Bump Version
      if: steps.check-pr-title.outputs.bump_version
      run: |
        VERSION_BUMP="${{ steps.check-pr-title.outputs.bump_version }}"
        echo "$VERSION_BUMP"
      
